= Migrate Drupal 7 to Wordpress 4 =

This cookbook migrates data from a Drupal database into a Wordpress database.

== Which data will be migrated? ==

The cookbook maps the following data between the two systems:

* users
* articles, pages
* comments

== Tested versions ==

This cookbook was tested with the following versions.

*Drupal*

* 7.38
* 7.39

*Wordpress*

* 4.2.2
* 4.3

== Adapt the cookbook ==

You can adapt specific settings of the cookbook. These settings should be
managed by using the Mapping Editor of the Tensei-Data frontend.

== Before the migration ==

Some `tables` of the Wordpress database must be empty to avoid key errors during
the migration process.

[source, sql]
----
TRUNCATE wp_users;
ALTER TABLE wp_users AUTO_INCREMENT = 1;
TRUNCATE wp_comments;
ALTER TABLE wp_comments AUTO_INCREMENT = 1;
TRUNCATE wp_posts;
ALTER TABLE wp_posts AUTO_INCREMENT = 1;
----

== After the migration ==

The passwords of the users are not migrated to the Wordpress system. If you want to
still have the admin password, you should save the content of the `user_pass` field
from the `users` table of the Wordpress database. You can store the password string
after the migration into the same field.
